### ISSUE TITLE
最新資料時間

### ISSUE THREAD

**Issue by paulin0613** [openfunltd/pcc-viewer#1]
有可能將最新資料時間更改為更即時嗎？

**Comment by ronnywang** [comment]
由於工程會網站會在晚上 12 點對前一天大量存取的 IP 做阻擋
如果我每天都爬一次的話，等於每天都需要換一次 IP ，這個會讓我爬的成本提高

所以我現在是一週只爬一次，這樣一週只要換兩次 IP 就好（一週爬一次要爬 30hr 左右）
暫時不考慮把每週頻率調到每日
（另外這週比較慢是因為工程會網站有小微調，因此我要調整我的爬蟲）
