### ISSUE TITLE
將 api_url 變成 config.js 以方便替換 API 網址

### ISSUE THREAD

**Issue by ronnywang** [openfunltd/pcc-viewer#2]
- 增加 config.js，並指定 api_url = 'https://pcc.g0v.ronny.tw'
- 將用到 pcc.g0v.ronny.tw 的部份，都改成 api_url

**Comment by typingmonk** [comment]
https://github.com/openfunltd/pcc-viewer/blob/6ccaae2819592b2fb22511993c62c7dac542a72c/search.html#L68
https://github.com/openfunltd/pcc-viewer/blob/6ccaae2819592b2fb22511993c62c7dac542a72c/searchbyid.html#L71
https://github.com/openfunltd/pcc-viewer/blob/6ccaae2819592b2fb22511993c62c7dac542a72c/searchbycompany.html#L71

以上三個 html 裡頭都有 declare `api_url` 在用
要不要把這些變數改名為 `query_url` （或其他名稱）避免去改到 `config.js` 裡頭宣告的變數 ?

https://github.com/openfunltd/pcc-viewer/blob/29870f8f24ddcba7ee12668efa27eacccac11b1d/config.js#L1

目前用 `const`去宣告 `config.js` 裡頭的變數，避免以後設定的變數被改動到

**Comment by ronnywang** [comment]
好啊，我建議改成 api_base = 'https://pcc.g0v.ronny.tw/' 好了

**Comment by typingmonk** [comment]
`issue2` 已 merge 進 `gh-pages`，請協助 review。網址是 https://openfunltd.github.io/pcc-viewer/

本次改動有牽涉到每一個 `.html` 檔案，以下是方便檢查確認的連結：

- [date.html](https://openfunltd.github.io/pcc-viewer/date.html?date=20230829)
- [index.html](https://openfunltd.github.io/pcc-viewer/index.html)
- [search.html](https://openfunltd.github.io/pcc-viewer/search.html?query=happy)
- [searchbycompany.html](https://openfunltd.github.io/pcc-viewer/searchbycompany.html?query=%E9%96%8B%E6%94%BE%E6%96%87%E5%8C%96%E5%9F%BA%E9%87%91%E6%9C%83)
- [searchbyid.html](https://openfunltd.github.io/pcc-viewer/searchbyid.html?query=05076416)
- [tender.html](https://openfunltd.github.io/pcc-viewer/tender.html?unit_id=3.79&job_number=1050204S0015)
- [unit.html](https://openfunltd.github.io/pcc-viewer/unit.html?unit_id=A.41)

**Comment by ronnywang** [comment]
感謝，確認 ok
