### ISSUE TITLE
Fix Space-to-Plus Conversion Issue in application/x-www-form-urlencoded Encoding

### ISSUE THREAD

**Issue by typingmonk** [openfunltd/pcc-viewer#3]
如題，在 input 中如果輸入包含空白的字串，依照 html 表單預設的 content type: `application/x-www-form-urlencoded`
會把 space 轉成 `+` 而不是 `%20`
使得在之後的 javascript `decodeURIComponent()` 跟 `encodeURIComponent()` 會把 space 當作 `+` 在處理。

### Reproduce Issue
1. 在 https://openfunltd.github.io/pcc-viewer/search.html 中的 `搜尋關鍵字` 輸入 "`開放` `資料`"
2. html 表單透過 `application/x-www-form-urlencoded` 將字串轉成 "`%E9%96%8B%E6%94%BE`**+**`%E8%B3%87%E6%96%99`"
3. L63 的 `decodeURIComponent()` 將字串轉成 "`開放`**+**`資料`"
4. L69 的 `encodeURIComponent()` 將字串轉成 "`%E9%96%8B%E6%94%BE`**%2B**`%E8%B3%87%E6%96%99`"
https://github.com/openfunltd/pcc-viewer/blob/543435ec98ad066120d58030e285e1e4484b6ea3/search.html#L62-L69
5. pcc api 收到的是 `%2B` 而不是 `%20`，以為收到的 input 是 `開放+資料` 而不是 `開放 資料`

### How to fix
在 `encodeURIComponent()` 之前先將 `+` 換成 space
```javascript
query = query.replace(/\+/g, ' ');
```

**Comment by ronnywang** [comment]
ok, 就這麼做吧
